name: knn-tent-clinic
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - numpy
  - scipy
  - matplotlib
  - pandas
  - scikit-learn
  - plotly
  - pytest
  - flake8
  - pip
  - setuptools
  - wheel
  - tqdm
  - ray-default
  - pip:
      - -e . # Install the current directory in editable mode
      - pytest-cov
      - pre-commit
