name: knn-tent-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - pip
  - setuptools
  - wheel
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - plotly
  - pytest
  - tqdm
  - debugpy
  - pip:
      - ray[default]
      - -e . # Install the current directory in editable mode
