[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "knn-tent-clinic"
version = "0.1.0"
description = "KNN-based tent clinic analysis"
authors = [{ name = "Juan F. Restrepo", email = "juan.restrepo@uner.edu.ar" }]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "numpy",
  "scipy",
  "pandas",
  "scikit-learn",
  "plotly",
  'ray[default]',
  'tqdm',
  'debugpy',
]

[project.urls]
Source = "https://github.com/jrestrepo86/knn-tent-clinic.git"
Repository = "https://github.com/jrestrepo86/knn-tent-clinic.git"

[project.optional-dependencies]
test = ["pytest>=6.2.0"]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["test*"]

[tool.setuptools.package-data]
"knn_tent_clinic" = ["data/*.txt", "data/*.csv"]
